# Generated by Django 6.0.4 on 2026-04-24 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('wy_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('cluj_is_home', models.BooleanField()),
                ('cluj_goals', models.IntegerField()),
                ('opp_goals', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['wy_id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('wy_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('is_cluj', models.BooleanField(default=False)),
                ('position_code', models.CharField(blank=True, default='', max_length=10)),
                ('appearances', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField()),
                ('position_code', models.CharField(blank=True, default='', max_length=10)),
                ('raw', models.JSONField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='insights.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='insights.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
