# Generated by Django 6.0.4 on 2026-04-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_current_squad',
            field=models.BooleanField(default=False),
        ),
    ]
