# Generated by Django 6.0.4 on 2026-04-25 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_player_in_current_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('session_name', models.CharField(max_length=255)),
                ('session_type', models.CharField(blank=True, default='', max_length=40)),
                ('duration_min', models.FloatField(default=0)),
                ('distance_m', models.FloatField(default=0)),
                ('work_rate', models.FloatField(default=0)),
                ('accel_low_pos', models.IntegerField(default=0)),
                ('accel_low_neg', models.IntegerField(default=0)),
                ('accel_high_pos', models.IntegerField(default=0)),
                ('accel_high_neg', models.IntegerField(default=0)),
                ('high_int_acc_m', models.FloatField(default=0)),
                ('high_int_dec_m', models.FloatField(default=0)),
                ('speed_15_20_m', models.FloatField(default=0)),
                ('speed_20_25_m', models.FloatField(default=0)),
                ('speed_25_50_m', models.FloatField(default=0)),
                ('power_avg_wkg', models.FloatField(default=0)),
                ('sprints_per_min', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='insights.player')),
            ],
            options={
                'ordering': ['date', 'session_name'],
                'indexes': [models.Index(fields=['player', 'date'], name='insights_tr_player__51a539_idx')],
                'unique_together': {('player', 'session_name')},
            },
        ),
    ]
